# Generated by Django 4.2.4 on 2023-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('property_img', models.FileField(upload_to='product_image')),
                ('property_place', models.CharField(max_length=20)),
                ('property_price', models.IntegerField()),
                ('property_address', models.CharField(max_length=100)),
            ],
        ),
    ]
