# Generated by Django 4.2.4 on 2023-08-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_front_end', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
